const cartItemsData = [{
	id: 'hghhghghg',
	img: 'images/img1.svg',
	absent: 'images/img-bw1.svg',
	name: 'Футболка UZcotton мужская',
	color: 'Цвет: белый',
	size: 'Размер: 56',
	stock: 'Коледино WB',
	company: 'OOO Вайлдберриз',
	price: 522,
	sale: 1051,
	left: 2,
},
{
	id: 'fkfkfkkff',
	img: 'images/img2.svg',
	absent: 'images/img-bw2.svg',
	name: 'Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe',
	color: 'Цвет: прозрачный',
	size: '',
	stock: 'Коледино WB',
	company: 'OOO Мегапрофстиль',
	price: 2100047,
	sale: 2300047,
	left: 100,
},
{
	id: 'rprprprprp',
	img: 'images/img3.svg',
	absent: 'images/img-bw3.svg',
	name: 'Карандаши цветные Faber-Castell "Замок", набор 24 цвета, заточенные, шестигранные, Faber-Castell',
	color: '',
	size: '',
	stock: 'Коледино WB',
	company: 'OOO Вайлдберриз',
	price: 494,
	sale: 950,
	left: 2,
}]
